name: Build Compose Android App on Feature Branch

on:
  push:
    branches: ["feature/**"]
  pull_request:
    branches: [main]

jobs:
  build-compose:
    name: Build Compose Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Compose Android App
        run: ./gradlew :androidApp:assembleDebug

      - name: Run Unit Tests
        run: ./gradlew :androidApp:testDebug
