name: Build Compose Android App on Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-main:
    name: Build Compose App for Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Compose App (Release)
        run: ./gradlew :androidApp:assembleRelease
